---
version: '3'
services:
  samba:
    container_name: samba
    image: dperson/samba
    restart: unless-stopped
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    volumes:
      - /media/storage/Public:/mount
      - samba_data:/run/samba
      - samba_data2:/var/lib/samba
      - samba_data3:/etc
      - samba_logs:/var/log/samba
      - samba_cache:/var/cache/samba
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: samba

    command: '-s "Mount;/mount;yes;no;no;admin" -u "admin;pass" -p'
volumes:
  samba_data: {}
  samba_data2: {}
  samba_data3: {}
  samba_logs: {}
  samba_cache: {}
