version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Riga'
      WEBPASSWORD: 'piholeadmin'
      PIHOLE_DNS_: '208.67.222.222;208.67.220.220'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_data2:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  pihole_data: {}
  pihole_data2: {}

