{
 "title": "Docker Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container Name",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"docker\", tag: \"container_name\", start: -1d)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"docker\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"docker_container_status\")\n  |> filter(fn: (r) => r._field == \"uptime_ns\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"docker\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field =~ /rx_bytes/)\n  |> filter(fn: (r) => r.container_name == \"${container_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> derivative(unit: 1s)\n  |> yield(name: \"_field\")"
    },
    {
     "query": "from(bucket: \"docker\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field =~ /tx_bytes/)\n  |> filter(fn: (r) => r.container_name == \"${container_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> derivative(unit: 1s)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"docker\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_mem\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> filter(fn: (r) => r.container_name == \"${container_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Cpu usage, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"docker\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_cpu\")\n  |> filter(fn: (r) => r._field == \"usage_percent\")\n  |> filter(fn: (r) => r.container_name == \"${container_name}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  }
 ]
}