
version: '3'
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    - ./passwd:/mosquitto/config/passwd:ro
    - mosquitto_data:/mosquitto/data
    - mosquitto_log:/mosquitto/log
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '1883:1883'
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    user: telegraf:997
    environment:
    - HOST_ETC=/hostfs/etc
    - HOST_PROC=/hostfs/proc
    - HOST_SYS=/hostfs/sys
    - HOST_VAR=/hostfs/var
    - HOST_RUN=/hostfs/run
    - HOST_MOUNT_PREFIX=/hostfs
    volumes:
    - /:/hostfs:ro
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - mosquitto
    links:
      - influxdb
      - mosquitto
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdbadmin
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafanaadmin
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
  mosquitto_data: {}
  mosquitto_log: {}

