{
 "title": "Docker Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Containers running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker\")\n  |> filter(fn: (r) => r._field =~ /n_containers_running*/)\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"docker_container_status\")\n  |> filter(fn: (r) => r._field == \"uptime_ns\")\n  |> aggregateWindow(every: 20s, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker\")\n  |> filter(fn: (r) => r._field =~ /n_containers.*/)\n  |> aggregateWindow(every: 20s, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker_container_mem\")\n  |> filter(fn: (r) => r._field == \"max_usage\")\n  |> aggregateWindow(every: 20s, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Cpu usage, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker_container_cpu\")\n  |> filter(fn: (r) => r._field == \"usage_percent\")\n  |> aggregateWindow(every: 20s, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field =~ /rx_bytes/)\n  |> aggregateWindow(every: 20s, fn: mean)\n  |> derivative(unit: 1s)\n  |> yield(name: \"_field\")"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field =~ /tx_bytes/)\n  |> derivative(unit: 1s)\n  |> yield(name: \"_field\")"
    }
   ]
  }
 ]
}