{
 "title": "Power Meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Phase 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"voltage\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"current\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"power\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"frequency\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._field == \"pf\")\n  |> filter(fn: (r) => r.phase == \"2\")\n  |> last()\n  |> yield(name: \"_field\")"
    }
   ]
  },
  { "title": "Historical Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"voltage\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"current\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"power\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"frequency\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"pf\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"_field\")"
    }
   ]
  }
 ]
}