version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: always
    environment:
      - TZ=Europe/Riga
    volumes:
      - ./config:/config
    ports:
      - '8123:8123'
    privileged: true
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: homeassistant
