---
version: "3"  

services:
    calibre:
        container_name: calibre
        image: wietsedv/calibre-server
        restart: unless-stopped
        volumes:
            - /Hidden/calibre:/library
        ports: 
            - "8080:8080"
        environment:
            - AJAX-TIMEOUT 900
            - TIMEOUT 900
            - MAX-JOB-TIME 0

