---
version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    command: --admin-password 'portaineradmin'
    ports:
      - 9000:9000/tcp
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: portainer

volumes:
  portainer_data: {}
