---
version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Riga
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=admin
      - PASS=transmissionadmin
    volumes:
      - transmission_data:/config
      - /Public:/downloads
      - /Public:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
volumes:
  transmission_data: {}

