---
version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Riga
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin
      - PASS=pass
    volumes:
      - transmission_data:/config
      - /Public:/downloads
      - /Public:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: transmission
volumes:
  transmission_data: {}
