---
version: "3"
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 1888:8080
    restart: unless-stopped
    environment:
      - TZ=Europe/Riga
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: zigbee2mqtt
