---
version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Riga
      - SERVERURL=192.168.1.3 #optional
      - SERVERPORT=51820 #optional
      - PEERS=MyPhone,MyPC #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.66.66.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: wireguard
