---
version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Riga
      - PLEX_CLAIM=myclaim
      - ADVERTISE_IP=http://192.168.1.3:32400/
    hostname: PlexServer
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - /media/storage/Public:/data
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.3:514"
        tag: plex

volumes:
  plex_transcode: {}
  plex_config: {}
